pepper_ips:  # Entry in dropdown menu will be create for every list item
  - 130.239.182.11  # pepper ip address, should be reachable from network where interface is hosted.
  - 130.239.182.10
  - 192.168.104.144
  - 10.42.0.75
  - 10.42.0.159
  - pepper.local


camera_save_dir: record_imgs  # relative folder on host machine, images form camera feed will be saved here
audio_save_dir: /home/nao/ # absolute path on pepper robot, you'll have scp or place audio files there yourself


# LOCK INTERFACE
# If you don't want all sections to be accessible, you can lock them, in which case they will be disabled for all input
# Can be useful if you don't fully trust the wizard and or when you just want to make sure not to mess with some settings
# on accident.
# Set 'true' and 'false' (JavaScript) as value, not Pythons True or False...
lock_autonomous_life_section: "false"
lock_movement_control_section: "false"
lock_tablet_section: "false"
lock_anim_speech_section: "false"
lock_volume_section: "false"
lock_audio_section: "false"
lock_gesture_section: "false"
lock_color_section: "false"
lock_eye_anim_section: "false"


# AUTONOMOUS LIFE SETTINGS
# Leave as empty string to leave value as is on connection to robot
# values must be valid for respective set methods in naoqi API...
autonomous_life_config:
  autonomous_state: "solitary"
  tangential_collision: ""
  orthogonal_collision: ""
  blinking: False  # can interfere with manual eye control...
  basic_awareness: False  # gets enabled by default if pepper enters solitary or interactive state...
  engagement_mode: ""
  head_breathing: False  # I would advise always having this disabled, conflicts with manual head control...
  arms_breathing: True
  body_breathing: True
  legs_breathing: True
  listening_movement: False
  speaking_movement: True

default_head_turn_deg: 20 # head turn increment
default_turn_deg: 90  # turn increment
default_drive_dist : 10  # move increment

# ALL CONCRETE ACTIONS (BUTTONS IN THE UI) CAN GET THE "key_comb" FIELD.
# PROVIDING A LIST WILL BIND THE KEYS IN THAT LAST TO THE CONCRETE ACTION TO EXECUTE
# SPECIAL KEYS CAN BE: "ctrl", "shift", "alt" etc, full list here: https://craig.is/killing/mice#keys
# example flag: key_comb: ["ctrl", "1"]  <-- Binds Control + 1 keyboard shortcut to an action
# ARROW KEY MAY NOT BE USED, AS THEY ARE ALREADY IN USE TO DRIVE PEPPER AND CONTROL THE HEAD AND HIP!!

tablet_root_location: static/tablet_items/  # place image or video files here, on host machine
tablet_items:
  -
    title: Timeline
    file_name: climate_change.jpg
    key_comb: ["ctrl", "shift", 1]  # example for more complex shortcut
  - 
    title: Landscape
    file_name: landscape.jpg
    key_comb: ["ctrl", "shift", 2]
  -
    title: Umea logo
    is_default_img: True  # image with this flag will be displayed on connect
    file_name: umea_logo.png
    key_comb: ["ctrl", "shift", 3]
  -
    title: Arrow keys
    file_name: arrow_keys.png
    key_comb: ["ctrl", "shift", 4]
  -
    title: Sound playing
    file_name: sound_playing.png
    key_comb: ["ctrl", "shift", 5]
  - 
    title: Local video  # Videos can also be played 
    file_name: mov_bbb.mp4  # file stored on host machine
    key_comb: ["ctrl", "shift", 6]
  - 
    title: Remote video
    file_name: http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4  # Remote file also possible, just put URL here
    key_comb: ["ctrl", "shift", 7]
  - 
    title: Website  # We can also show a website on Pepper's tablet
    file_name: https://www.google.com/  # Also just put URL to website here
    key_comb: ["ctrl", "shift", 8]
  -
    title: Confused cat
    file_name: https://i.kym-cdn.com/photos/images/facebook/001/564/773/6cf.jpg
    key_comb: ["ctrl", "shift", 9]


animated_speech:
    # Avoid special characters in messages, this can break the backend.
    # EG: Instead if a ', put &apos; into the message, which is the HTML symbol for the apostroph
  
  - 
    title: BEGIN
    string: "Hello, it is very nice to meet you! My name is Pepper. How are you?"
    tooltip: "Voice pitch annotated change"
    key_comb: ["ctrl", "aw"]
  - 
    title: IM GOOD. WHAT IS UR NAME
    string: "That's great to hear! I'm feeling good today too! Tell me a bit about yourself - what is your name?"
    tooltip: "Voice pitch annotated change"
    key_comb: ["ctrl", "aw"]  
  - 
    title: IM OKAY. WHAT IS UR NAME
    string: "Yeah me too. Tell me a bit about yourself - what is your name?"
    tooltip: "Voice pitch annotated change"
    key_comb: ["ctrl", "aw"]  
  - 
    title: IM BAD. WHAT IS UR NAME
    string: "I am sorry to hear that. Hopefully I can help to cheer you up a little bit! Tell me a bit about yourself - what is your name?"
    tooltip: "Voice pitch annotated change"
    key_comb: ["ctrl", "aw"]  
  - 
    title: Are student YES
    string: "And what do you study?"
    tooltip: "Voice pitch annotated change"
    key_comb: ["ctrl", "ww"]
  - 
    title: Are student NO
    string: "And what do you work as?"
    tooltip: "Voice pitch annotated change"
    key_comb: ["ctrl", "ww"]
  - 
    title: Enjoy study YES
    string: "It is great to do something you are passionate about! What country are you from?"
    tooltip: "Voice pitch annotated change"
    key_comb: ["ctrl", "ww"]
  - 
    title: Enjoy study NO
    string: "University can be hard sometimes. I'm sure you will get through it! What country are you from?"
    tooltip: "Voice pitch annotated change"
    key_comb: ["ctrl", "ww"]
  - 
    title: Where live?
    string: "Nice! I am from France. Do you live in Glasgow or a bit further out?"
    tooltip: "Voice pitch annotated change"
    key_comb: ["ctrl", "ww"]
  - 
    title: Any holidays?
    string: "Cool. I have enjoyed Glasgow since coming here at joining the university! Do you have any holidays
            planned over summer?"
    tooltip: "Voice pitch annotated change"
    key_comb: ["ctrl", "ww"]
  - 
    title: Holidays Yes
    string: "Oh nice! It is fun to get away and explore. My most recent travelling has always been in taxi about Glasgow.
              Are you in any societies or sports clubs?"
    tooltip: "Voice pitch annotated change"
    key_comb: ["ctrl", "ww"] 
  - 
    title: Holidays No
    string: "It is nice to stay home. My most recent travelling has always been in taxi about Glasgow.
              Are you in any societies or sports clubs?"
    tooltip: "Voice pitch annotated change"
    key_comb: ["ctrl", "ww"]
  - 
    title: Societies Yes
    string: "Nice! It is good to spend time with other people. I had an idea - can we play some games?"
    tooltip: "Voice pitch annotated change"
    key_comb: ["ctrl", "we"]
    
  - 
    title: Societies No
    string: "It is nice to just relax by yourself too. I had an idea - can we play some games?"
    tooltip: "Voice pitch annotated change"
    key_comb: ["ctrl", "wf"]
  -
    title: Start vocal warmup
    string: "Okay. Let's do a vocal warmup - but you can lead! I want you to say a sentence and I will repeat it
            back to you."
    tooltip: "Voice pitch annotated change"
    key_comb: ["ctrl", "wg"]
  - 
    title: PLets play 20 Qs # This will be shown in the GUI
    string: "That was fun! Can we play 20 Questions now please? Do you know the game?"  # message pepper will say
    tooltip: "Plain message without annotations"  # tooltip for the button in UI
    key_comb: ["ctrl", "1"]  # keyboard shortcut for this action
  - 
    title: Rules 20 Qs # This will be shown in the GUI
    string: "One player thinks of an object. The other player can ask up to 20 Yes or No questions to try and guess what the other player is thinking of. Makes sense?"  # message pepper will say
    tooltip: "Plain message without annotations"  # tooltip for the button in UI
    key_comb: ["ctrl", "1"]  # keyboard shortcut for this action
  - 
    title: Start 20Qs
    string: "Okay. I will think of the object and you can guess. Go!"
    tooltip: "Voice pitch annotated change"
    key_comb: ["ctrl", "2"]
  - 
    title: Yes General
    string: "^start(animations/Stand/Gestures/Yes_1) Yes"
    tooltip: "Voice pitch annotated change"
    key_comb: ["ctrl", "wa"]
      
  - 
    title: No General
    string: "^start(animations/Stand/Gestures/No_1) No"
    tooltip: "Voice pitch annotated change"
    key_comb: ["ctrl", "ws"]
  -
    title: Win 20Qs
    string: "Well done, that's right. I was thinking of a TIGER. Can we play one more game?"
    tooltip: "Voice speed annotated change"
    key_comb: ["ctrl", "3"]
  -
    title: Fail 20Qs
    string: "Out of questons! I was thinking of a TIGER. Can we play one more game?"
    tooltip: "Hello there! ^start(animations/Stand/Gestures/Hey_1) I am over here. ^wait(animations/Stand/Gestures/Hey_1)"
    key_comb: ["ctrl", "4"]
  -
    title:  Do you know rules Hangman
    string: "Okay! Let's play Hangman. Do you know the rules?"
    tooltip: "Hello there! ^start(animations/Stand/Gestures/Hey_1) I am over here. ^wait(animations/Stand/Gestures/Hey_1)"
    key_comb: ["ctrl", "5"] 
  -
    title:  Rules hangman
    string: "One player thinks of a word. The other player can guess letters to try and figure out the word. You have six wrong guesses. Makes sense?"
    tooltip: "Hello there! ^start(animations/Stand/Gestures/Hey_1) I am over here. ^wait(animations/Stand/Gestures/Hey_1)"
    key_comb: ["ctrl", "5"]
  -
    title: Finish experiment
    string: "Me too! I think our time is up. I am getng tired now I'm afraid. It was nice to meet you, have a good day! ^start(animations/Stand/Gestures/Hey_3) "
    tooltip: "Look at me! ^run(animations/Stand/Gestures/ShowSky_8) I am this tall!"
    key_comb: ["ctrl", "6"]
  

volume: 0.5  # range: [0.0 - 1.0], default = 1
voice_speed: 100  # range [50 - 400], default = 100
voice_pitch: 1 # range [1.0 - 4.0], default = 1, 0 disables effect


gestures: # Buttons will be created for every item in the list
  -
    title: "Yes"  # This will be shown in the GUI
    gesture: "animations/Stand/Gestures/Yes_1"  # Gesture to execute
    tooltip: "Yes_1 gesture"  # Tooltip for buton
    key_comb: ["shift", "1"]
  -
    title: "No"
    gesture: "animations/Stand/Gestures/No_1"
    tooltip: "No_1 gesture"
    key_comb: ["shift", "2"]
  -
    title: "Wave"
    gesture: "animations/Stand/Gestures/Hey_3"
    tooltip: "Hey_3 gesture"
    key_comb: ["shift", "3"]
  -
    title: "Me"
    gesture: "animations/Stand/Gestures/Me_1"
    tooltip: "Me_1 gestzre"
    key_comb: ["shift", "4"]
  -
    title: "You"
    gesture: "animations/Stand/Gestures/You_1"
    tooltip: "You_1 gesture"
    key_comb: ["shift", "5"]
  -
    title: "Embarrassed"
    gesture: "animations/Stand/Emotions/Neutral/Embarrassed_1"
    tooltip: "Embarrassed_1 gesture"
    key_comb: ["shift", "6"]

  -
    title: "Happy"
    gesture: "animations/Stand/Emotions/Positive/Happy_4"
    tooltip: "blah"
    key_comb: ["shift", "7"]

colors:
  # Color values for eye leds that should be accessable from the interface
  # one color may have the 'is_default: true' flag, which will then be set as color for the eye leds once interface connects to robot
  # Values will be rounded to two decimals places...
  -
    title: Red  # will be shown in UI, alongside small box that takes given RGB value
    red: 1.0
    green: 0
    blue: 0
    key_comb: ["c", "r"]
  -
    title: Yellow
    red: 1.0
    green: 1.0
    blue: 0
    key_comb: ["c", "y"]
  -
    title: Orange
    red: 1.0
    green: 0.7
    blue: 0
    key_comb: ["c", "o"]
  -
    title: Green
    red: 0
    green: 1.0
    blue: 0
    key_comb: ["c", "g"]
    is_default: True  # default color will be set on connect
  -
    title: Aqua
    red: 0
    green: 1.0
    blue: 1.0
    key_comb: ["c", "a"]
  -
    title: Blue
    red: 0
    green: 0
    blue: 1.0
    key_comb: ["c", "b"]
  -
    title: Magenta
    red: 1.0
    green: 0
    blue: 1.0
    key_comb: ["c", "m"]
  -
    title: White
    red: 1.0
    green: 1.0
    blue: 1.0
    key_comb: ["c", "w"]

# Eye animation configuration
# these are further configurable, because there are only those three animations available
rasta_anim:
  duration: 3
  key_comb: ["ctrl", "alt", 1]

random_anim:
  duration: 6
  key_comb: ["ctrl", "alt", 2]

rotate_anim:
  duration: 4
  key_comb: ["ctrl", "alt", 3]
